name: crystalsizer3d

channels:
  - conda-forge
  - pytorch
  - https://conda.ccdc.cam.ac.uk

dependencies:
  - python = 3.9
  - csd-python-api = 3.1
  - ffmpeg-python = 0.2
  - filelock = 3.13
  - matplotlib = 3.8
  - mayavi = 4.8
  - numpy = 1.26
  - pillow = 9.5
  - python-dotenv = 1.0
  - pytorch = 2.3
  - pyyaml = 6.0
  - rtree = 1.2
  - tensorboard = 2.15
  - timm = 0.9
  - torchvision = 0.18
  - trimesh = 4.1
  - pip
  - pip:
    - cholespy == >= 1.0, < 1.1
    - gigagan-pytorch >= 0.2, < 0.3
    - gpytoolbox >= 0.2, < 0.3
    - kornia >= 0.7, < 0.8
    - manifold3d >= 2.4, < 2.5
    - mitsuba >= 3.5, < 3.6
    - opencv-python >= 4.9, < 5.0
    - parti-pytorch >= 0.2, < 0.3
    - pyfastnoisesimd >= 0.4, < 0.5
    - pymatgen >= 2024.8, < 2024.9
    - python-fcl >= 0.7, < 0.8
    - pytorch-minimize >= 0.0.2, < 0.1
    - transformers >= 4.37, < 4.38
    - wxpython >= 4.2, < 4.3
